# Generated by Django 4.0.3 on 2022-03-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=5000),
        ),
    ]
