# Generated by Django 4.0.3 on 2022-03-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_course_owner_remove_course_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sections',
            field=models.ManyToManyField(related_name='courses', to='app.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(related_name='sections', to='app.lesson'),
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users', to='app.course'),
        ),
    ]
